### ISSUE TITLE
Swift 3.0 Error Class doesn't exists 

### ISSUE THREAD

**Issue by cesarbecerra** [raulriera/TextFieldEffects#112]
<img width="329" alt="captura de pantalla 2016-12-14 a la s 08 44 34" src="https://cloud.githubusercontent.com/assets/3884564/21186291/a03f9b38-c1d9-11e6-965b-5854594e5416.png">

Am getting the next issue and i cannot see the styles

**Comment by m2jobe** [comment]
Facing this same issue too when I import the TextFieldEffects into my current project, the textfields arent responsive and dont work as expected (no error is outputted except the above). However when trying via the demo provided it works fine? Are we missing any necessary steps?

**Comment by raulriera** [comment]
Hi,

Could you provide the steps you are doing? in detail place

**Comment by m2jobe** [comment]
I found a fix, rather than setting the module to "TextFieldEffects", setting it to your project name and then setting the textfield class to AnimatableTextField first before setting it to any of the other TextFieldEffects will make it work and make sure to customize the textfield itself afterwards to notice the change.

**Comment by raulriera** [comment]
Sounds like you are doing way more than just using the library? What is AnimatableTextfield? Setting the module would be the way to do it only if you are using the library in its default behavior
