### ISSUE TITLE
Objective-C usage

### ISSUE THREAD

**Issue by AladinWay** [raulriera/TextFieldEffects#15]
I really like the library and the effects, but how can I implement this in my Objective-C project (Xcode 6, iOS 8)

**Comment by raulriera** [comment]
Hi, did you follow the installation instructions? there is nothing "Swift only" about this project

**Comment by AladinWay** [comment]
Any guidance to integrate it with objective C project ?

**Comment by raulriera** [comment]
I still don't understand the question, all you need to do is add the library to your project (it doesn't matter if you are using Swift or Objective-C, Swift works with both) and just use it normally like the installation instructions say.

For creating the Bridging header to use Swift inside Objective-C you can follow this guide https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by AladinWay** [comment]
Sorry, here is a good video for those who wants to integrate this Framework in their Objective C projects : https://www.youtube.com/watch?v=afT92TQYpLQ

**Comment by billy84** [comment]
Hi @raulriera 
I have Objective-C project and I want to add this pod into my project.
Would you mind to share sample Objective-C project in xCode 7.3?
I am not sure how I can use this really.

Hope to hear from you soon

Regards

**Comment by Cokile** [comment]
Hey billy84

The APIs for Objective-C are exactly the same as Swift except the syntax. You just create a new instance of one effect and customise the appearance with the same properties. All the extra work is to create a bridge header, you can refer the link raulriera provided above.

If you still could not work out how to use the library with Objective-C project at the end, you could try the Objective-C version:https://github.com/Cokile/CCTextFieldEffects. I ported it to Objective-C and added some extra effects. Personally, I recommend you to use raulriera's rather than mine because mine don't support Interface Builder.

**Comment by raulriera** [comment]
Nice work Cokile, they look awesome. Love the block syntax sugar too

**Comment by billy84** [comment]
Thanks guys!
