### ISSUE TITLE
effects not working at right time

### ISSUE THREAD

**Issue by khandkashivam** [raulriera/TextFieldEffects#167]
text fields not animating in latest swift...
like in hoshiTextFieldEffect, while editing text field the placeholder doesnt goes up, but after ending the edit.. then the placeholder text goes up..help me

**Comment by mdmack** [comment]
(COPIED FROM Autocomplete Issued)
@khandkashivam 
I have weird issues as well where the animation is repeating from the placeholder to the text when a field is filled in but it no longer has focus, however I found a workaround. May not work for you, but it might be a root cause.

First, iI=f you look at the pod file TextFieldEffects.swift you'll see this:
override open func draw(_ rect: CGRect) {
// FIXME: Short-circuit if the view is currently selected. iOS 11 introduced
// a setNeedsDisplay when you focus on a textfield, calling this method again
// and messing up some of the effects due to the logic contained inside these
// methods.
// This is just a "quick fix", something better needs to come along.
guard isFirstResponder == false else { return }
drawViewsForRect(rect)
}

In my class (that was copied from MadokaTextField.swift) I added this function override and the animation stops and it looks perfect. Again, may not help but it might be related.

override open func draw(_ rect: CGRect) {
// TODO: This fix was taken from the same function in TextFieldEffects.swift. I overrode it and
// added a check if the text is empty, which works until the pod is updated.
guard isFirstResponder == false else { return }
// This prevents the constant redraw
if text!.isEmpty {
drawViewsForRect(rect)
}
}
