### ISSUE TITLE
Autocomplete error

### ISSUE THREAD

**Issue by nacho1309** [raulriera/TextFieldEffects#168]
I'm having an issue when using autocomplete with HoshiTextField, whenever I am on an active HoshiTextField and I press an item to autocomplete, the textfield gets smashed with the placeholder like if there was no text.
Steps to reproduce
-Tap on an active HoshiTextField to allow typing
-Select an autocomplete field on the keyboard

**Comment by mdmack** [comment]
I have weird issues as well where the animation is repeating from the placeholder to the text when a field is filled in but it no longer has focus, however I found a workaround.  May not work for you, but it might be a root cause.

First, iI=f you look at the pod file TextFieldEffects.swift you'll see this:
`   override open func draw(_ rect: CGRect) {
		// FIXME: Short-circuit if the view is currently selected. iOS 11 introduced
		// a setNeedsDisplay when you focus on a textfield, calling this method again
		// and messing up some of the effects due to the logic contained inside these
		// methods.
		// This is just a "quick fix", something better needs to come along.
		guard isFirstResponder == false else { return }
		drawViewsForRect(rect)
    }`

In my class (that was copied from MadokaTextField.swift) I added this function override and the animation stops and it looks perfect. Again, may not help but it might be related.

`  override open func draw(_ rect: CGRect) {
    // TODO: The FIXME was taken from TextFieldEffects.swift.  I overrode it and
    // added a check if the text is empty, which works until the pod is updated.
    //
    // FIXME: Short-circuit if the view is currently selected. iOS 11 introduced
    // a setNeedsDisplay when you focus on a textfield, calling this method again
    // and messing up some of the effects due to the logic contained inside these
    // methods.
    // This is just a "quick fix", something better needs to come along.
    guard isFirstResponder == false else { return }
    // This prevents the constant redraw
    if text!.isEmpty {
      drawViewsForRect(rect)
    }
  }`

**Comment by nacho1309** [comment]
Ended up using another library, tried the fix but didn't work for me.

**Comment by nacho1309** [comment]
Ended up using another library, tried the fix but didn't work for me.
