### ISSUE TITLE
Change Placeholder to attributed font

### ISSUE THREAD

**Issue by rp9994** [raulriera/TextFieldEffects#195]
I unable to change the attributed font. how can I can change the same

**Comment by raulriera** [comment]
Hi, please provide more detailed description of what you are trying to do

**Comment by rp9994** [comment]
i want to create like this

![Screenshot 2019-11-27 at 3 13 54 PM](https://user-images.githubusercontent.com/17848613/69712373-b74f1a00-1128-11ea-9b6b-3e46b6c30576.png)

**Comment by raulriera** [comment]
For that you will have to modify the code, there is option to supply an attributed text for the placeholder

**Comment by julien-tamade** [comment]
Hi, I'm also having trouble adjusting the placeholder text. You say there is an option, but when I try to I get the error `CoreText note: Client requested name ".SFUI-Regular", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[UIFont systemFontOfSize:].` I am trying to make my sign in form compatible with dark mode. Thank You.

**Comment by raulriera** [comment]
The error message is properly telling you what is going on, have you tried fixing the font first?

**Comment by julien-tamade** [comment]
Yeah I'm trying `emailInput.attributedPlaceholder = NSAttributedString(string: "Test Email", attributes: [NSAttributedString.Key.foregroundColor: UIColor.red, NSAttributedString.Key.font: UIFont.systemFont(ofSize: 40)])` where emailInput is a HoshiTextField, but neither the color nor size attributes are affecting the placeholder text

**Comment by raulriera** [comment]
Ah I see, `emailInput.attributedPlaceholder` is a property of UITextField directly and bypassing the values in this library. You need to use

`placeholderFontScale` to change the size
`placeholderColor` to change the color

This library doesn't support changing the font via attributed text, is its a combination of those 2 properties mentioned and using the normal `font` property

**Comment by julien-tamade** [comment]
ah thank you!
